const characters = [
  {
    cast: 'main',
    name: 'Tony Hawk',
    city: 'San Diego, California',
    position: 'Pateta',
    style: 'Vert',
    perfil: 'images/profile/thumb_skater-tony-hawk.jpg',
    thumb:'images/thumb/Tony.jpg',
    videoLink: 'https://www.youtube.com/embed/4TRwCUUB-y4',
    char: 'images/skaters/TonyHawk.png'
  },
  {
    cast: 'main',
    name: 'Jamie Thomas',
    city: 'Dothan, Alabama',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-jamie-thomas.jpg',
    thumb:'images/thumb/Jamie.jpg',
    videoLink: 'https://www.youtube.com/embed/VaM49N5kbYk',
    char: 'images/skaters/JamieThomas.png'
  },
  {
    cast: 'main',
    name: 'Andrew Reynolds',
    city: 'North Hollywood, California',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-andrew-reynolds.jpg',
    thumb:'images/thumb/reynolds.jpg',
    videoLink: 'https://www.youtube.com/embed/MxCSlT95Dsg',
    char: 'images/skaters/AndrewReynolds.png'
  },
  {
    cast: 'main',
    name: 'Kareem Campbell',
    city: 'Harlem, New York, NY',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-kareem-campbell.jpg',
    thumb:'images/thumb/kareem.jpg',
    videoLink: 'https://www.youtube.com/embed/Zv6YAS88oRc',
    char: 'images/skaters/KareemCampbell.png'
  },
  {
    cast: 'main',
    name: 'Elissa Steamer',
    city: 'San Francisco, California',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-elissa-steamer.jpg',
    thumb:'images/thumb/steamer.jpg',
    videoLink: 'https://www.youtube.com/embed/SKYgYXUghkc',
    char: 'images/skaters/ElissaSteamer.png'
  },
  {
    cast: 'main',
    name: 'Bob Burnquist',
    city: 'Rio de Janeiro, Brasil',
    position: 'Reg',
    style: 'Vert',
    perfil: 'images/profile/thumb_skater-bob-burnquist.jpg',
    thumb:'images/thumb/Bob.jpg',
    videoLink: 'https://www.youtube.com/embed/LyidJ9Eq2cI',
    char: 'images/skaters/BobBurnQuist.png'
  },
  {
    cast: 'main',
    name: 'Bucky Lasek',
    city: 'Baltimore, Maryland',
    position: 'Reg',
    style: 'Vert',
    perfil: 'images/profile/thumb_skater-bucky-lasek.jpg',
    thumb:'images/thumb/Bucky.jpg',
    videoLink: 'https://www.youtube.com/embed/D2aq-EtvCNU',
    char: 'images/skaters/BuckyLasek.png'
  },
  {
    cast: 'main',
    name: 'Rune Glifberg',
    city: 'Copenhagen, Denmark',
    position: 'Reg',
    style: 'Vert',
    perfil: 'images/profile/thumb_skater-rune-glifberg.jpg',
    thumb:'images/thumb/Rune.jpg',
    videoLink: 'https://www.youtube.com/embed/X_HHzNMnJ14',
    char: 'images/skaters/RuneGlifberg.png'
  },
  {
    cast: 'main',
    name: 'Geoff Rowley',
    city: 'Liverpool, United Kingdom',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-geoff-rowley.jpg',
    thumb:'images/thumb/rowley.jpg',
    videoLink: 'https://www.youtube.com/embed/Yds5G5b7Kus',
    char: 'images/skaters/GeoffRowley.png'
  },
  {
    cast: 'main',
    name: 'Chad Muska',
    city: 'Los Angeles, California',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-chad-muska.jpg',
    thumb:'images/thumb/muska.jpg',
    videoLink: 'https://www.youtube.com/embed/Pg5O1a5rBFU',
    char: 'images/skaters/ChadMuska.png'
  },
  {
    cast: 'main',
    name: 'Rodney Mullen',
    city: 'Gainesville, Florida',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-rodney-mullen.jpg',
    thumb:'images/thumb/rodney.jpg',
    videoLink: 'https://www.youtube.com/embed/HThBks1dbKA',
    char: 'images/skaters/RodneyMullen.png'
  },
  {
    cast: 'main',
    name: 'Steve Caballero',
    city: 'San Jose, California',
    position: 'Pateta',
    style: 'Vert',
    perfil: 'images/profile/thumb_skater-steve-caballero.jpg',
    thumb:'images/thumb/caballero.jpg',
    videoLink: 'https://www.youtube.com/embed/qR6XmEBSGCQ',
    char: 'images/skaters/steveCaballero.png'
  },
  {
    cast: 'main',
    name: 'Eric Koston',
    city: 'San Bernardino, California',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-eric-koston.jpg',
    thumb:'images/thumb/Koston.jpg',
    videoLink: 'https://www.youtube.com/embed/Rm1f6AfOPBE',
    char: 'images/skaters/EricKoston.png'
  },
  {
    cast: 'new',
    name: 'Nyjah Huston',
    city: 'Laguna Beac, California',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-nyjah-huston.jpg',
    thumb:'images/thumb/nyjah.jpg',
    videoLink: 'https://www.youtube.com/embed/OuUv1G-rk8E',
    char: 'images/skaters/NyjahHuston.png'
  },
  {
    cast: 'new',
    name: 'Leticia Bufoni',
    city: 'São Paulo, Brasil',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-letica-bufoni.jpg',
    thumb:'images/thumb/leticia.jpg',
    videoLink: 'https://www.youtube.com/embed/rWx1zXet1Ow',
    char: 'images/skaters/LeticiaBufoni.png'
  },
  {
    cast: 'new',
    name: 'Lizzie Armanto',
    city: 'Santa Monica, California',
    position: 'Reg',
    style: 'Pista',
    perfil: 'images/profile/thumb_skater-lizzie-armanto.jpg',
    thumb:'images/thumb/Lizzie.jpg',
    videoLink: 'https://www.youtube.com/embed/BQC7pyagVS0',
    char: 'images/skaters/LizzieArmanto.png'
  },
  {
    cast: 'new',
    name: 'Aori Nishimura',
    city: 'Tokyo, Japan',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-aori-nishimura.jpg',
    thumb:'images/thumb/Aori.jpg',
    videoLink: 'https://www.youtube.com/embed/T1vaHxS3fb0',
    char: 'images/skaters/AoriNishimura.png'
  },
  {
    cast: 'new',
    name: "Shane O'Neil",
    city: 'Melbourne, Australia',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-shane-oneill.jpg',
    thumb:'images/thumb/Shane.jpg',
    videoLink: 'https://www.youtube.com/embed/WpduqrnYYvs',
    char: 'images/skaters/ShaneOneil.png'
  },
  {
    cast: 'new',
    name: "Leo Baker",
    city: 'Covina, California',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-leo-baker.jpg',
    thumb:'images/thumb/Leo.jpg',
    videoLink: 'https://www.youtube.com/embed/uL5_aT4k6J0',
    char: 'images/skaters/LeoBaker.png'
  },
  {
    cast: 'new',
    name: "Riley Hawk",
    city: 'San Diego, California',
    position: 'Pateta',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-riley-hawk.jpg',
    thumb: 'images/thumb/Riley.jpg',
    videoLink: 'https://www.youtube.com/embed/S7dJ5QQ6Dm8',
    char: 'images/skaters/RileyHawk.png'
  },
  {
    cast: 'new',
    name: "Tyshawn Jones",
    city: 'Bronx, New York',
    position: 'Reg',
    style: 'Rua',
    perfil: 'images/profile/thumb_skater-tyshawn-jones.jpg',
    thumb: 'images/thumb/Tyshawn.jpg',
    videoLink: 'https://www.youtube.com/embed/EkxVC6WWArE',
    char: 'images/skaters/TyshawnJones.png'
  },
]
export default characters;